### ISSUE TITLE
This is interesting

### ISSUE THREAD

**Issue by shtefcs** [MohamedHmini/iww#2]
Hey Mohamed, this is interesting repo. ARe you still working on it? Do you have some plans for future development?

Peace,

**Comment by MohamedHmini** [comment]
oh thanks, yeah i still have some plans for that, it's not done for sure but i've finished the first part of it for a bachelor's degree thesis.
i'm glad that u r interested in that project, for a sake of clarification the initial goal of this library is to help people to get what they want from the web using advanced algorithms and hopefully the latest A.I ones.
i'm open for new ideas and if u need any explanation of what i've been doing it would be my please to help u out.

**Comment by shtefcs** [comment]
I was researching about Ai web scraping for a project I am working on [Automatio](https://automatio.co) and found your repo. Ai vision web extraction is interesting concept, still new for me, but trying to explore much.

Would like to connect with you further with possible collaboration work.

My email is stefan@vanila.io

**Comment by MohamedHmini** [comment]
i've seen the project u've mentioned and i'm certainly astonished by ur web-scrapping service, but keep in mind that my ideas r for goal-directed fully-automated web-scrapping based algorithms, which means no manual supervision is needed for reaching the goal (for instance, extracting the most relevant text-bloc, or extracting the mean data-regions/ data-records ...) for the purpose of enabling greater services like search engines.
i would like to help u out and u can reach me through email of course.

**Comment by shtefcs** [comment]
YEah, I am aware of the purpose of your library. That is why I was researching about Ai web data extraction. 

Reaching you over email.
